import Head from 'next/head';
import Image from 'next/image';

import Profile from '../components/profile';
import Link from 'next/link';

export default function Home() {
  return (
    <div className="bg-orange-100 flex flex-col justify-between h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main className="bg-orange-200">
          <div className="bg-orange-300 p-3 flex justify-between">
            <div className="text-2xl">Zona Segura</div>
            <Profile />
          </div>
          <h1 className="bg-orange-400 p-4">
            Bienvenido al canal de denuncias: es seguro y completamente anónimo
          </h1>
        </main>
      </div>

      <footer className="bg-orange-300 p-3">
        <a href="https://zitadel.ch" target="_blank" rel="noopener noreferrer">
          Powered by Chewy
        </a>
      </footer>
    </div>
  );
}
