'use client';
import { useState } from 'react';

import './global.css';

import { MainLayout } from './MainLayout';
import { RootState, setTheme } from '@coba/redux-store';
import { useDispatch, useSelector } from 'react-redux';
import { StoreProvider } from '@coba/components';

// export const metadata = {
//   title: 'Automotriza Coba',
//   description: 'Generated by create-nx-workspace',
// };

const themes = [
  'light',
  'dark',
  'cupcake',
  'bumblebee',
  'emerald',
  'corporate',
  'synthwave',
  'retro',
  'cyberpunk',
  'valentine',
  'halloween',
  'garden',
  'forest',
  'aqua',
  'lofi',
  'pastel',
  'fantasy',
  'wireframe',
  'black',
  'luxury',
  'dracula',
  'cmyk',
  'autumn',
  'business',
  'acid',
  'lemonade',
  'night',
  'coffee',
  'winter',
  'dim',
  'nord',
  'sunset',
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <Content>{children}</Content>
    </StoreProvider>
  );
}
function Content({ children }: any) {
  const dispatch = useDispatch();
  const { theme } = useSelector((state: RootState) => state.shoppingCart);
  return (
    <html lang="es" data-theme={theme}>
      <head>
        <title>Coba</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <select
          onChange={(e) => dispatch(setTheme(e.target.value))}
          defaultValue={theme}
        >
          {themes.map((s) => (
            <option key={s} value={s}>
              {s}
            </option>
          ))}
        </select>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
