/* eslint-disable @next/next/no-sync-scripts */
import { Header } from '@coba/components';
import './global.css';

export const metadata = {
  title: 'Welcome to coba',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Coba</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
}
